# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Symfony\Bridge\Twig\Mime\TemplatedEmail: ~

    app.dto.email.gmail:
        class: App\DTO\Email\ViewParameters
        arguments:
            $textPathTemplate: 'email/text.html.twig'
            $htmlPathTemplate: 'email/html.html.twig'

    app.service.email.sender_view:
        class: App\Service\Email\EmailSenderView


    app.dto.email.gmail.email_parameters:
        class: App\DTO\Email\EmailParameters
        arguments:
            $viewParameters: '@app.dto.email.gmail'

    app.service.email.gmail.factory:
        class: App\Service\Email\GmailEmailFactory
        arguments:
            $emailParameters: '@app.dto.email.gmail.email_parameters'

    App\Controller\Card:
        tags: [controller.service_arguments]
        bind:
            $viewParameters: '@app.dto.email.gmail'

    App\Command\GmailSendMail:
        class: App\Command\GmailSendMail
        arguments:
            $emailSender: '@app.service.email.sender_view'
            $emailFactory: '@app.service.email.gmail.factory'
            $logger: '@logger'
